
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres
development:
  <<: *default
  database: instaclone_development

test:
  <<: *default
  database: instaclone_test
  
production:
  <<: *default
  database: instaclone_production
  username: instaclone
  password: <%= ENV["INSTACLONE_DATABASE_PASSWORD"] %>
